apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-guestbook-backend
  labels:
    app: java-guestbook
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: java-guestbook
        tier: backend
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: pubsub-key
      containers:
      - name: backend
        image: java-guestbook-backend
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "2Gi"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: PORT
          value: "8080"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
